# Generated by Django 5.2.1 on 2025-05-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='delete',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='delete',
            new_name='deleted',
        ),
    ]
